In [1]:
import re
str1='imoocnum 1000'
info=re.search(r'\d+',str1)
info.group()

'1000'

In [6]:
info=re.sub(r'(\d+?P=<aa>)',(?P=aa),str1)
info

SyntaxError: invalid syntax (<ipython-input-6-8805e88320b8>, line 1)

In [8]:
import urllib2

In [9]:
page=urllib2.urlopen('http://www.imooc.com/')
page

<addinfourl at 72574736 whose fp = <socket._fileobject object at 0x045401B0>>

In [10]:
buf=page.read()
buf

'\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n<meta charset="utf-8">\r\n<title>\xe6\x85\x95\xe8\xaf\xbe\xe7\xbd\x91-\xe7\xa8\x8b\xe5\xba\x8f\xe5\x91\x98\xe7\x9a\x84\xe6\xa2\xa6\xe5\xb7\xa5\xe5\x8e\x82</title>\r\n<meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">\r\n<meta name="renderer" content="webkit" />\r\n<meta property="qc:admins" content="77103107776157736375" />\r\n<meta property="wb:webmaster" content="c4f857219bfae3cb" />\r\n<meta http-equiv="Access-Control-Allow-Origin" content="*" />\r\n<meta http-equiv="Cache-Control" content="no-transform " />\r\n<meta http-equiv="Content-Security-Policy" content="script-src \'self\' \'unsafe-inline\' \'unsafe-eval\' *.imooc.com *.mukewang.com *.baidu.com *.sina.com.cn *.bootcss.com">\r\n<link rel="dns-prefetch" href="//www.imooc.com" />\r\n<link rel="dns-prefetch" href="//img.imooc.com" />\r\n<link rel="dns-prefetch" href="//img.mukewang.com" />\r\n<link rel="apple-touch-icon" sizes="76x76" href="/static/img/common/touch-icon-i

In [14]:
urllist=re.findall(r'http:.+\.jpg',buf)
urllist

['http://climg.mukewang.com/5836c00a0001916906000338.jpg',
 'http://szimg.mukewang.com/583e42fb0001e04f05400300-360-202.jpg',
 'http://szimg.mukewang.com/596324dc00016bcc05400300-360-202.jpg',
 'http://img.mukewang.com/591d59cc0001a3c706000338-240-135.jpg',
 'http://climg.mukewang.com/5993e8880001521206000338.jpg',
 'http://szimg.mukewang.com/598d52730001aaf205400300-360-202.jpg',
 'http://szimg.mukewang.com/592789e30001fdf305400300-360-202.jpg',
 'http://img.mukewang.com/57cfa226000150c206000338-240-135.jpg',
 'http://climg.mukewang.com/599cdb6200018f1e06000338.jpg',
 'http://szimg.mukewang.com/5938b0f100016a9e05400300-360-202.jpg',
 'http://szimg.mukewang.com/59313618000198ed05400300-360-202.jpg',
 'http://img.mukewang.com/590a8c9400013c5406000338-240-135.jpg',
 'http://img.mukewang.com/572afe280001c13406000338-240-135.jpg',
 'http://szimg.mukewang.com/594b37170001cd6b05400300-360-202.jpg',
 'http://szimg.mukewang.com/586359c00001af9005400300-360-202.jpg',
 'http://img.mukewang.com/5

In [18]:
i=0
for url in urllist:
    f= open(str(i)+'.jpg','wb')
    req=urllib2.urlopen(url)
    buf=req.read()
    f.write(buf)
    i=i+1

In [20]:
# -*- coding:utf-8 -*-
import re, urllib2

request = urllib2.urlopen('http://www.imooc.com/')
buf = request.read()
listurl = re.findall(r'src=.+\.jpg',buf)
print listurl
res=[]
for url in listurl:
    a= re.findall(r'http:.+\.jpg',url)
    res.append(a[0])

for url in res:
    print url
index = 0
for url in res:
    f = open('h'+str(index)+'.jpg', 'wb')
    request = urllib2.urlopen(url)
    buf = request.read()
    f.write(buf)
    index = index + 1

['src="http://climg.mukewang.com/5836c00a0001916906000338.jpg', 'src="http://szimg.mukewang.com/583e42fb0001e04f05400300-360-202.jpg', 'src="http://szimg.mukewang.com/596324dc00016bcc05400300-360-202.jpg', 'src="http://img.mukewang.com/591d59cc0001a3c706000338-240-135.jpg', 'src="http://climg.mukewang.com/5993e8880001521206000338.jpg', 'src="http://szimg.mukewang.com/598d52730001aaf205400300-360-202.jpg', 'src="http://szimg.mukewang.com/592789e30001fdf305400300-360-202.jpg', 'src="http://img.mukewang.com/57cfa226000150c206000338-240-135.jpg', 'src="http://climg.mukewang.com/599cdb6200018f1e06000338.jpg', 'src="http://szimg.mukewang.com/5938b0f100016a9e05400300-360-202.jpg', 'src="http://szimg.mukewang.com/59313618000198ed05400300-360-202.jpg', 'src="http://img.mukewang.com/590a8c9400013c5406000338-240-135.jpg', 'src="http://img.mukewang.com/572afe280001c13406000338-240-135.jpg', 'src="http://szimg.mukewang.com/594b37170001cd6b05400300-360-202.jpg', 'src="http://szimg.mukewang.com/58635

HTTPError: HTTP Error 400: Bad Request

In [23]:
import urllib2,re
page=urllib2.urlopen('http://www.imooc.com/course/list')
buf=page.read()
urllist=re.findall(r'http:.+\.jpg',buf)
urllist


['http://img.mukewang.com/529dc3380001379906000338-240-135.jpg" src="http://img.mukewang.com/529dc3380001379906000338-240-135.jpg',
 'http://img.mukewang.com/57035ff200014b8a06000338-240-135.jpg" src="http://img.mukewang.com/57035ff200014b8a06000338-240-135.jpg',
 'http://img.mukewang.com/53e1d0470001ad1e06000338-240-135.jpg" src="http://img.mukewang.com/53e1d0470001ad1e06000338-240-135.jpg',
 'http://img.mukewang.com/574669dc0001993606000338-240-135.jpg" src="http://img.mukewang.com/574669dc0001993606000338-240-135.jpg',
 'http://img.mukewang.com/53a28e960001311b06000338-240-135.jpg" src="http://img.mukewang.com/53a28e960001311b06000338-240-135.jpg',
 'http://img.mukewang.com/570360620001390f06000338-240-135.jpg" src="http://img.mukewang.com/570360620001390f06000338-240-135.jpg',
 'http://img.mukewang.com/53daee770001dd0706000338-240-135.jpg" src="http://img.mukewang.com/53daee770001dd0706000338-240-135.jpg',
 'http://img.mukewang.com/540e57300001d6d906000338-240-135.jpg" src="http://

In [5]:
a=map(lambda x : x + 1, [1, 2, 3])

In [3]:
import numpy as np

a=np.random.rand(100)
print(a)

[ 0.14893011  0.20069676  0.50632888  0.09820369  0.23402767  0.08153819
  0.20147814  0.46239903  0.3338704   0.48639525  0.57956945  0.88394573
  0.85790678  0.22588892  0.35358738  0.86924066  0.36829137  0.55124799
  0.89406814  0.66948543  0.81010426  0.82049313  0.42655149  0.44378755
  0.52034828  0.78732264  0.33400874  0.42002228  0.61890919  0.6925792
  0.30253532  0.51422842  0.7631238   0.36226114  0.30554504  0.40446607
  0.58051772  0.64699905  0.3939173   0.69468624  0.86284801  0.13567658
  0.21003494  0.56848967  0.25797661  0.3956691   0.29396136  0.13102511
  0.79514526  0.31992783  0.32275845  0.84269481  0.84712048  0.78161894
  0.74082931  0.56110594  0.64424842  0.24746527  0.47997535  0.72310937
  0.81706722  0.41708084  0.53499752  0.90615492  0.78081286  0.40962611
  0.94943001  0.05656492  0.62434537  0.47628945  0.03994993  0.95161438
  0.70251558  0.87724181  0.52637933  0.23624082  0.1670127   0.7696361
  0.7740599   0.75711656  0.48184279  0.58671197  0.8

In [16]:
import time

a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic=time.time()
z=np.dot(a.T,b)
toc=time.time()

tm=(toc-tic)*1000
print(tm)

2.984285354614258


In [17]:
a=np.random.rand(3,4)

In [18]:
print(a)

[[ 0.17622822  0.79758693  0.39081438  0.55520123]
 [ 0.75833041  0.29188143  0.86681776  0.39775404]
 [ 0.95753425  0.56648517  0.31876652  0.52080079]]


In [19]:
cal=a.sum(axis=0)
print(cal)

[ 1.89209289  1.65595354  1.57639866  1.47375606]


In [20]:
percentage=100*a/cal
print(percentage)

[[  9.31393075  48.16481337  24.79159564  37.67253257]
 [ 40.07892103  17.62618505  54.98721728  26.98913666]
 [ 50.60714821  34.20900158  20.22118708  35.33833078]]


In [22]:
percentage=100*a/cal.reshape(1,4)
print(percentage)

[[  9.31393075  48.16481337  24.79159564  37.67253257]
 [ 40.07892103  17.62618505  54.98721728  26.98913666]
 [ 50.60714821  34.20900158  20.22118708  35.33833078]]


In [24]:
import numpy as np

import matplotlib.pyplot as plt

import sklearn

import sklearn.datasets

# from init_utils import sigmoid, relu, compute_loss, forward_propagation, backward_propagation

# from init_utils import update_parameters, predict, load_dataset, plot_decision_boundary, predict_dec



%matplotlib inline

plt.rcParams['figure.figsize'] = (7.0, 4.0) # set default size of plots

plt.rcParams['image.interpolation'] = 'nearest'

plt.rcParams['image.cmap'] = 'gray'


# load image dataset: blue/red dots in circles

train_X, train_Y, test_X, test_Y = load_dataset()

NameError: name 'load_dataset' is not defined